### ISSUE TITLE
Preprocessing Problem about N4BiasFieldCorrection module

### ISSUE THREAD

**Issue by biyoner** [xf4j/brats18#1]
Hello,
When I run the preprocessing code,  while getting an IOError: **No command "N4BiasFieldCorrection" found.** Is there any configuration problem or something wrong with my code?

**Comment by parvezamu** [comment]
First installed antsbin in your home directory....then cd brats18...then write  export PATH=${PATH}:$Home/antsbin/bin in terminal in case of Ubuntu....after that python pre_processing.py /path to your dataset...it will take more than 5 hours......

**Comment by biyoner** [comment]
Thanks !

**Comment by chengjianhong** [comment]
> First installed antsbin in your home directory....then cd brats18...then write export PATH=${PATH}:$Home/antsbin/bin in terminal in case of Ubuntu....after that python pre_processing.py /path to your dataset...it will take more than 5 hours......

Hi, can you tell me how to begin to traing after preprocessed data? I hava switched python2.7,but it doesn't work.
